const states = {
    Intro_Screen: 0,
    Outside_Shop_1: 1,
    Outside_Shop_2: 2,
    Near_Aisle: 3,
    Shopping: 4,
    Billing_Start: 5,
    Accept_Offer: 6,
    Enter_Bargain: 7,
    Bargain_Low: 8,
    Bargain_MidLow: 9,
    Bargain_MidHigh: 10,
    Bargain_High: 11,
    Bargain_Highest: 12,
    Decline_Offer: 13,
    Failed_Purchase: 14,
    Successful_Purchase: 15,
    GameOver: 16,
}